/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChuyenDe;
import model.KhoaHoc;
import service.KhoaHocService;

/**
 *
 * @author hungj
 */
public class QuanLyKhoaHoc extends javax.swing.JFrame {

    private KhoaHocService KHSV = new KhoaHocService();
    DefaultTableModel model = new DefaultTableModel();
    int index;

    public QuanLyKhoaHoc() {
        initComponents();
        setLocationRelativeTo(null);

        model = (DefaultTableModel) tblQLKhoahoc.getModel();
        this.fillDataToTable(KHSV.getAll());
        for (ChuyenDe cd : KHSV.getChuyenDe()) {
            cboMaCD.addItem(cd.getCD());
        }
        if (tblQLKhoahoc.getRowCount() > 0) {
            index = tblQLKhoahoc.getRowCount() - 1;
            showDetail(index);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtMaKH = new javax.swing.JTextField();
        txtThoiluong = new javax.swing.JTextField();
        txtNgaytao = new javax.swing.JTextField();
        cboMaCD = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLKhoahoc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quan ly khoa hoc");

        jLabel2.setText("Ma khoa hoc");

        jLabel3.setText("Thoi luong");

        jLabel4.setText("Ngay tao");

        jLabel5.setText("Ma chuyen de");

        btnTim.setText("Tim Thoi Luong");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        cboMaCD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblQLKhoahoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma KH", "Ngay tao", "Ma CD", "Thoi Luong"
            }
        ));
        tblQLKhoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLKhoahocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLKhoahoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnTim))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnSua)
                                        .addGap(54, 54, 54)
                                        .addComponent(btnXoa))
                                    .addComponent(txtThoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cboMaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboMaCD, txtMaKH, txtNgaytao, txtThoiluong});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboMaCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLKhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLKhoahocMouseClicked
        // TODO add your handling code here:
        index = tblQLKhoahoc.getSelectedRow();
        showDetail(index);
    }//GEN-LAST:event_tblQLKhoahocMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
//        int thoiLuongTK = Integer.parseInt(txtThoiluong.getText());
//        fillDataToTable(KHSV.timKiem(thoiLuongTK));
//        if (tblQLKhoahoc.getRowCount() > 0) {
//            index = 0;
//            showDetail();
//        }
//        JOptionPane.showMessageDialog(this, "Tìm thành công");

        int thoiLuong = Integer.parseInt(txtThoiluong.getText());
        fillDataToTable(KHSV.timKiem(thoiLuong));
        if (tblQLKhoahoc.getRowCount() > 0) {
            index = 0;
            showDetail(index);
            JOptionPane.showMessageDialog(this, "tim thay thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Khong tim thay");

        }

    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        KhoaHoc kh = readForm();

        if (KHSV.addNguoiHoc(kh) != null) {
            fillDataToTable(KHSV.getAll());
            if (tblQLKhoahoc.getRowCount() > 0) {
                index = tblQLKhoahoc.getRowCount() - 1;
//                index = 0;
                showDetail(index);
            }
            JOptionPane.showMessageDialog(this, "Thêm thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ");
            return;
        }
        if (readForm() != null) {
            int i = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá kHông");
            if (i == JOptionPane.YES_OPTION) {
                KHSV.xoa(readForm());
                model.removeRow(index);
                fillDataToTable(KHSV.getAll());
                JOptionPane.showMessageDialog(this, "Xoa Thành Công");

            } else {
                JOptionPane.showMessageDialog(this, "Thoát");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất Bại");
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        boolean k = true;
        for (KhoaHoc kh : KHSV.getAll()) {
            if (kh.getMaKH() == Integer.parseInt(txtMaKH.getText())) {
                k = false;
            }
        }

        if (k) {
            JOptionPane.showMessageDialog(this, "Mã không được sửa");
            txtMaKH.requestFocus();
            return;
        } else {
            KhoaHoc kh = readForm();
            if (KHSV.update(kh) != null) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                fillDataToTable(KHSV.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
            }
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhoaHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaCD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLKhoahoc;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgaytao;
    private javax.swing.JTextField txtThoiluong;
    // End of variables declaration//GEN-END:variables

    private void fillDataToTable(ArrayList<KhoaHoc> list) {
        model.setRowCount(0);
        for (KhoaHoc kh : list) {
            model.addRow(kh.toDataRow());
        }
    }

    private void showDetail(int i) {
        txtMaKH.setText(model.getValueAt(i, 0).toString());
        txtNgaytao.setText(model.getValueAt(i, 1).toString());
        cboMaCD.setSelectedItem(model.getValueAt(i, 2).toString());
        txtThoiluong.setText(model.getValueAt(i, 3).toString());

    }

    private KhoaHoc readForm() {
        KhoaHoc kh = new KhoaHoc();
        kh.setMaKH(Integer.parseInt(txtMaKH.getText()));
        kh.setThoiLuong(Integer.parseInt(txtMaKH.getText()));
        kh.setNgayLap(txtNgaytao.getText());
        kh.setMaCD((String) cboMaCD.getSelectedItem());

        return kh;
    }

}
