/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;
import model.NguoiHoc;
import model.SoDienThoai;
import service.NguoiHocService;

/**
 *
 * @author hungj
 */
public class QuanLyNguoiHoc extends javax.swing.JFrame {

    private NguoiHocService NHSV = new NguoiHocService();
    private DefaultTableModel model = new DefaultTableModel();
    int index;

    /**
     * Creates new form QuanLyNguoiHoc
     */
    public QuanLyNguoiHoc() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblQuanLyNH.getModel();
        this.fillDataToTable(NHSV.getAll());
        for (SoDienThoai sdt : NHSV.getSoDienThoai()) {
            cboSDT.addItem(sdt.getSdt());
        }
        if (tblQuanLyNH.getRowCount() > 0) {
//            index = NHSV.getAll().size() - 1;
            index = tblQuanLyNH.getRowCount() - 1;
//            index = 0;
            showDetail(index);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        txtNgaysinh = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        cboSDT = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyNH = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MA NGUOI HOC");

        jLabel2.setText("Quan Ly Nguoi Hoc");

        jLabel3.setText("NGAY SINH");

        jLabel4.setText("GIOI TINH");

        jLabel5.setText("SO DIEN THOAI");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("Ho va ten");

        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTim)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnTim)
                .addGap(26, 26, 26))
        );

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nu");

        tblQuanLyNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "HoTen", "Gioi tinh", "Ngay Sinh", "So dien thoai"
            }
        ));
        tblQuanLyNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyNHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyNH);

        btnThem.setText("ADD");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("UPDATE");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("DELETE");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cboSDT, 0, 121, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(rdoNam)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa)
                                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQuanLyNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyNHMouseClicked
        // TODO add your handling code here:

        index = tblQuanLyNH.getSelectedRow();
        showDetail(index);
    }//GEN-LAST:event_tblQuanLyNHMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String hoTen = txtHoTen.getText().trim();
        if (NHSV.timKiem(hoTen).isEmpty()) {
            JOptionPane.showMessageDialog(this, "khong tim thay");
        } else {
            this.fillDataToTable(NHSV.timKiem(hoTen));
            JOptionPane.showMessageDialog(this, "ds tim thay trong bang");
        }

    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        for (NguoiHoc nh : NHSV.getAll()) {
            if (nh.getMaNH().equals(txtMa.getText())) {
                JOptionPane.showMessageDialog(this, "Mã CD không được trùng");
                txtMa.requestFocus();
                return;
            }
        }
        if (txtMa.getText().trim().equals("")
                || txtHoTen.getText().trim().equals("")
                || txtNgaysinh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập đủ thông tin đi");
            requestFocus();
            return;
        } else {
            NguoiHoc nh = ReadForm();
            NHSV.addNguoiHoc(nh);
            JOptionPane.showMessageDialog(this, "Đã Thêm");
            this.fillDataToTable(NHSV.getAll());
            index = 0;
            showDetail(index);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
//        try {
//            NguoiHoc nh = ReadForm();
//            if ( NHSV.updteNguoiHoc(nh)) {
//                JOptionPane.showMessageDialog(this, "Cập nhật thông tin sinh viên thành công");
////                NHSV.getAll();
//                fillDataToTable(NHSV.getAll());
//            } else {
//                JOptionPane.showMessageDialog(this, "Cập nhật thông tin sinh viên thất bại");
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi. Vui lòng thử lại.");
//        }

        boolean k = false;
        for (NguoiHoc nh : NHSV.getAll()) {
            String m = txtMa.getText().toString().trim();
            if (nh.getMaNH().trim().equals(m)) {
                k = true;
                break;
            }
        }

        if (!k) {
            JOptionPane.showMessageDialog(this, "Mã không được sửa");
            txtMa.requestFocus();
            return;
        } else {
            NguoiHoc kh = ReadForm();
            if (NHSV.updteNguoiHoc(kh) != null) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                fillDataToTable(NHSV.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
            }
        }


    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        index = tblQuanLyNH.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ");
            return;
        }
        if (ReadForm() != null) {
            int i = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá kHông");
            if (i == JOptionPane.YES_OPTION) {
                NHSV.xoa(ReadForm());
                model.removeRow(index);
                fillDataToTable(NHSV.getAll());
                JOptionPane.showMessageDialog(this, "Xoa Thành Công");

            } else {
                JOptionPane.showMessageDialog(this, "Thoát");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất Bại");
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNguoiHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboSDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblQuanLyNH;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaysinh;
    // End of variables declaration//GEN-END:variables

    private void fillDataToTable(ArrayList<NguoiHoc> list) {

        model.setRowCount(0);
        for (NguoiHoc nh : list) {
            model.addRow(nh.toDataRow());
        }

//        for (NguoiHoc nh : NHSV.getAll()) {
//            String gioiTinh = nh.isGioiTinh() ? "Nam" : "Nu";
//            model.addRow(new Object[]{
//                nh.getMaNH(),
//                nh.getHoTen(),
//                gioiTinh,
//                nh.getNamSinh(),
//                nh.getSdt(),});
//        }
    }

    private void showDetail(int i) {

        txtMa.setText((String) model.getValueAt(i, 0).toString().trim());
        txtHoTen.setText((String) model.getValueAt(i, 1).toString());
//        rdoNam.setSelected((boolean) model.getValueAt(i, 2));
        String gender = model.getValueAt(i, 2).toString().trim();
        if (gender.equals("Nam")) {
            rdoNam.setSelected(true);
            rdoNu.setSelected(false);
        } else {
            rdoNu.setSelected(true);
            rdoNam.setSelected(false);

        }
//        rdoNu.setSelected(!(boolean) model.getValueAt(i, 2));
        txtNgaysinh.setText((String) model.getValueAt(i, 3).toString());
        cboSDT.setSelectedItem(tblQuanLyNH.getValueAt(i, 4).toString());
        tblQuanLyNH.setRowSelectionInterval(index, index);

//        NguoiHoc nh = NHSV.getAll().get(index);
//        rdoNam.setSelected(nh.isGioiTinh());
//        rdoNu.setSelected(!nh.isGioiTinh());
//        txtMa.setText(nh.getMaNH());
//        txtHoTen.setText(nh.getHoTen());
//        txtNgaysinh.setText(nh.getNamSinh());
//        cboSDT.setSelectedItem(nh.getSdt());
//        tblQuanLyNH.setRowSelectionInterval(index, index);
    }

    private NguoiHoc ReadForm() {
        NguoiHoc nh = new NguoiHoc();
//        nh.setMaNH(Integer.parseInt(txtMa.getText()));
        nh.setMaNH(txtMa.getText());
        nh.setHoTen(txtHoTen.getText());
        nh.setNamSinh(txtNgaysinh.getText());
        nh.setSdt((String) cboSDT.getSelectedItem());

        if (rdoNam.isSelected()) {
            nh.setGioiTinh(true);
        } else {
            nh.setGioiTinh(false);
        }
        return nh;
    }
}
